version: '3.6'
services:
  db:
    image: postgres:latest
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - sharyn-net
  redis:
    image: redis:latest
    volumes:
      - ./data/redis:/data
    ports:
      - '6379:6379'
    networks:
      - sharyn-net
networks:
  sharyn-net:
    name: sharyn-net
